remote_theme: just-the-docs/just-the-docs
title: Factory Thread Docs
description: The Factory Thread documentation
logo: "/images/ft-logo.png"
favicon_ico: "/images/favicon.ico"

search_enabled: true
color_scheme: dark

aux_links:
  "Factory Thread":
    - "//factorythread.com"
  "Docs Repository":
    - "//github.com/snicsolutions/factorythread-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable the side/mobile menu globally
nav_enabled: true

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_repository: "https://github.com/snicsolutions/factorythread-docs"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"
