title: Factory Thread Documentation
description: Complete documentation for Factory Thread - your comprehensive development platform
baseurl: "/factorythread-docs"
url: "https://snicsolutions.github.io"

remote_theme: just-the-docs/just-the-docs
color_scheme: light

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 3
  preview_words_after: 3

heading_anchors: true

nav_enabled: true

aux_links:
  "Factory Thread":
    - "//factorythread.com"
  "GitHub Repository":
    - "//github.com/snicsolutions/factorythread-docs"

aux_links_new_tab: true

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %l:%M %p"

gh_edit_link: true
gh_edit_repository: "https://github.com/snicsolutions/factorythread-docs"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

footer_content: 'Copyright &copy; 2024 Factory Thread. Distributed by an <a href="https://github.com/snicsolutions/factorythread-docs/tree/main/LICENSE.txt">MIT license.</a>'

plugins:
  - jekyll-feed
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
